"""
This module defines the Generator class, which is responsible for generating
responses using a Language Model based on a given context and conversation history.
"""

from typing import Any, Dict, List, Optional, Tuple

from ollama import chat

from source.config import LLM_MODEL_NAME
from source.utils import GENERATOR_SYSTEM_PROMPT


class Generator:
    """
    Handles the generation of responses using an Ollama-powered Language Model.

    This class constructs a detailed prompt including the conversation history
    and retrieved context, then calls the Ollama API to generate a final,
    context-aware answer.

    Attributes:
        model_name (str): The name of the Ollama model to use for generation.
        system_prompt (str): The system prompt that guides the LLM's behavior.
        messages (Optional[Dict[str, List[Any]]]): The conversation history.
        reranked_docs (Optional[List[Tuple[float, Any]]]): A list of tuples,
            each containing a relevance score and a retrieved document object.
    """

    def __init__(self) -> None:
        """Initializes the Generator."""
        self.model_name: str = LLM_MODEL_NAME
        self.system_prompt: str = GENERATOR_SYSTEM_PROMPT
        self.messages: Optional[Dict[str, List[Any]]] = None
        self.reranked_docs: Optional[List[Tuple[float, Any]]] = None

    def _build_context(self) -> str:
        """
        Constructs the context string from the reranked documents.

        Assumes that each document object in `reranked_docs` has a
        `page_content` attribute.

        Returns:
            str: A single string containing the concatenated content of all
                 retrieved documents.
        """
        if not self.reranked_docs:
            return ""
        
        context_parts: List[str] = [doc.page_content for _, doc in self.reranked_docs]
        return "\n".join(context_parts)

    def _build_conversation_history(self) -> str:
        """
        Constructs the conversation history string.

        Excludes the most recent user message, as it is the current query.

        Returns:
            str: A formatted string of the past user and AI interactions.
        """
        if not self.messages:
            return ""

        user_messages: List[Any] = self.messages.get("User", [])[:-1]
        ai_messages: List[Any] = self.messages.get("AI", [])
        
        history_parts: List[str] = []
        for i in range(min(len(user_messages), len(ai_messages))):
            history_parts.append(f"User: {user_messages[i]}")
            history_parts.append(f"AI: {ai_messages[i]}")
            
        return "\n".join(history_parts)

    def _build_user_prompt(self) -> str:
        """
        Constructs the final user prompt to be sent to the LLM.

        This prompt includes the current query, the retrieved context, and
        the conversation history (if any).

        Returns:
            str: The fully constructed prompt for the LLM.
        """
        if not self.messages:
            return ""
            
        query: Any = self.messages.get("User", [])[-1]
        context: str = self._build_context()
        history: str = self._build_conversation_history()

        if history:
            return f"""
Previous Conversation History:
{history}

Answer the question based ONLY on the following context:
{context}

Question:
{query}
"""
        else:
            return f"""
Answer the question based ONLY on the following context:
{context}

Question:
{query}
"""

    def generate(
        self, messages: Dict[str, List[Any]], reranked_docs: List[Tuple[float, Any]]
    ) -> str:
        """
        Generates a response from the LLM.

        Args:
            messages (Dict[str, List[Any]]): The conversation history.
            reranked_docs (List[Tuple[float, Any]]): The list of retrieved and
                                                     reranked documents.

        Returns:
            str: The content of the message generated by the LLM.
        """
        self.messages = messages
        self.reranked_docs = reranked_docs

        try:
            response = chat(
                model=self.model_name,
                messages=[
                    {"role": "system", "content": self.system_prompt},
                    {"role": "user", "content": self._build_user_prompt()},
                ],
                stream=False,
            )
            return response["message"]["content"]
        except Exception as e:
            print(f"Error during LLM generation: {e}")
            return "Sorry, I encountered an error while generating a response."
